# Generated by Django 3.1.7 on 2021-04-17 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BLOGING_APP', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NavigationFields',
            new_name='NavigationField',
        ),
    ]
