# Generated by Django 3.1.7 on 2021-04-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOGING_APP', '0002_auto_20210417_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCreation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_Title', models.CharField(max_length=30)),
                ('Details', models.CharField(max_length=300)),
            ],
        ),
    ]
