# Generated by Django 3.1.7 on 2021-05-05 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoAPP', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodoMODELS',
            new_name='Instruction',
        ),
    ]
