# Generated by Django 3.1.7 on 2021-05-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoAPP', '0002_auto_20210505_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='Text',
            field=models.CharField(max_length=500),
        ),
    ]
