# Generated by Django 3.1.7 on 2021-05-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoAPP', '0003_auto_20210506_0010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instruction',
            old_name='Text',
            new_name='Text_M',
        ),
        migrations.AlterField(
            model_name='instruction',
            name='Complete',
            field=models.BooleanField(default='False'),
        ),
    ]
