# Generated by Django 3.1.7 on 2021-05-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoAPP', '0008_auto_20210506_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='User_name',
            field=models.CharField(max_length=100, verbose_name='auth.User'),
        ),
    ]
