# Generated by Django 3.1.7 on 2021-05-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoAPP', '0014_auto_20210506_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='User_name',
            field=models.CharField(default='False', max_length=100, verbose_name='auth.User'),
        ),
    ]
