# Generated by Django 3.1.7 on 2021-05-06 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoAPP', '0018_auto_20210506_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instruction',
            old_name='User_name',
            new_name='User_name_id',
        ),
    ]
