# Generated by Django 3.1.7 on 2021-05-06 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoAPP', '0019_auto_20210506_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='User_name_id',
        ),
    ]
