# Generated by Django 3.1.7 on 2021-05-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoAPP', '0023_auto_20210506_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='Complete',
            field=models.BooleanField(default='NULL'),
        ),
    ]
