# Generated by Django 3.1.7 on 2021-05-06 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoAPP', '0024_auto_20210506_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='Complete',
        ),
    ]
