# Generated by Django 3.1.7 on 2021-05-06 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoAPP', '0026_auto_20210506_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructions',
            name='Complete',
        ),
    ]
