# Generated by Django 3.1.7 on 2021-07-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POST_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
