# Generated by Django 3.1.7 on 2021-07-26 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POST_app', '0003_auto_20210726_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentlist',
            name='Date',
        ),
    ]
