# Generated by Django 3.1.7 on 2021-07-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POST_app', '0004_remove_appointmentlist_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentlist',
            name='Date',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
