# Generated by Django 3.1.7 on 2021-07-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POST_app', '0005_appointmentlist_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentlist',
            name='RequiredSpeciality',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
