# Generated by Django 3.1.7 on 2021-07-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POST_app', '0006_appointmentlist_requiredspeciality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentlist',
            name='start_time',
            field=models.TimeField(max_length=200, null=True),
        ),
    ]
