# Generated by Django 3.1.7 on 2021-07-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POST_app', '0007_auto_20210727_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentlist',
            name='end_time',
            field=models.TimeField(max_length=200, null=True),
        ),
    ]
