# Generated by Django 3.1.7 on 2021-05-11 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Title_M', models.CharField(max_length=200, null=True)),
                ('Details_M', models.TextField(max_length=500, null=True)),
                ('ImagesM', models.FileField(blank=True, upload_to='images/')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('User_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_Name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment', models.CharField(max_length=200, null=True)),
                ('Commented_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('User_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post_ID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='BlogAPP.instruction')),
            ],
        ),
    ]
