# Generated by Django 3.1.7 on 2021-05-13 09:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogAPP', '0002_instruction_likes_m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='Details_M',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
