# Generated by Django 3.1.7 on 2021-05-13 11:52

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BlogAPP', '0003_auto_20210513_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Google_Add_Sense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Compeny_Name', models.CharField(max_length=200, null=True)),
                ('ADD', models.FileField(blank=True, upload_to='Google-ADD/')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Clicking', models.ManyToManyField(related_name='Google_Add_Sense', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
