# Generated by Django 3.1.7 on 2021-05-17 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogAPP', '0006_auto_20210513_1821'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cetegorys',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='Cetegory',
            new_name='Category_Field',
        ),
    ]
